experimentName: nni_score
searchSpaceFile: search_space_score.json
trialCommand: python nni_score.py
trialCodeDirectory: .
trialConcurrency: 8
maxExperimentDuration: 24h
maxTrialNumber: 1000
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: False