experimentName: nni_score
searchSpaceFile: search_space.json
trialCommand: python nni_score.py
trialCodeDirectory: .
trialConcurrency: 1
maxExperimentDuration: 48h
maxTrialNumber: 100
tuner:
  name: TPE
  classArgs:
    optimize_mode: maximize
trainingService:
  platform: local
  useActiveGpu: False